Architecture and error checking.

diff --git a/packages/base/all/vendor-config-onl/src/bin/onlfit b/packages/base/all/vendor-config-onl/src/bin/onlfit
--- a/packages/base/all/vendor-config-onl/src/bin/onlfit
+++ b/packages/base/all/vendor-config-onl/src/bin/onlfit
@@ -5,9 +5,28 @@ if [ -z "$1" ]; then
     exit 1
 fi
 
+ARCH=`uname -m`
+case $ARCH in
+    armv7l|ppc)
+    ;;
+    *)
+    echo "This script cannot be used on $ARCH platforms."
+    exit 1
+    ;;
+esac
+
 PLATFORM=$(cat /etc/onl/platform)
 
 dir=`mktemp -d`
-(cd $dir && wget $1)
-onlfs rw boot mv $dir/* /mnt/onl/boot/${PLATFORM}.itb
+rc=
+
+if (cd $dir && wget $1); then
+    onlfs rw boot mv $dir/* /mnt/onl/boot/${PLATFORM}.itb
+    rc=0
+else
+    echo "Download failed."
+    rc=1
+fi
+
 rmdir $dir
+exit $rc
